### ISSUE TITLE
Error about libNeuroML dependency, even though it's installed

### ISSUE THREAD

**Issue by travs** [NeuroML/pyNeuroML#11]
Followed the setup instructions in the readme. 

Trying:

```
$ pynml
Traceback (most recent call last):
  File "/usr/local/bin/pynml", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 3070, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 3056, in _call_aside
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 3083, in _initialize_master_working_set
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 647, in _build_master
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 660, in _build_from_requirements
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 833, in resolve
pkg_resources.DistributionNotFound: The 'libNeuroML>=0.2.5' distribution was not found and is required by pyNeuroML
```

And yet:

```
$ pip list
airspeed (0.5.4.dev20150515)
cachetools (0.8.0)
funcsigs (0.4)
libNeuroML (0.2.9)             <- hmm
lxml (3.4.4)
matplotlib (1.4.3)
mock (1.3.0)
nose (1.3.7)
numpy (1.9.2)
pbr (1.4.0)
pip (7.1.0)
PyLEMS (0.3.7)
pyNeuroML (0.1.1)
pyparsing (2.0.3)
python-dateutil (2.4.2)
pytz (2015.4)
setuptools (15.0)
six (1.9.0)
```

I've not had this error before. 
Fresh virtualenv, OSX.

Anything I can do to help test this further?

**Comment by pgleeson** [comment]
@travs, I've made some changes to the install scripts since this, please let me know if it's still an issue.

**Comment by sanjayankur31** [comment]
Hi @travs : are you still seeing this issue? (otherwise we'll close this ticket).
