### ISSUE TITLE
[Bug] NetPyNe 1.0.1 doesn't work with pyNeuroML

### ISSUE THREAD

**Issue by jonrkarr** [NeuroML/pyNeuroML#163]
Environment
- pyNeuroML 0.5.20
- pyLems 0.5.9
- NetPyNe 1.0.1
- Neuron 8.0.2

The same environment, except with NetPyNe 1.0.0.2, works fine.

```
 jNeuroML >>  (INFO) NRN Error  >>> Traceback (most recent call last):
  jNeuroML >>  (INFO) NRN Error  >>>   File "/tmp/tmpfxjbyyg4/fixtures/tmpddygkrlp_netpyne.py", line 193, in <module>
  jNeuroML >>  (INFO) NRN Error  >>>     ns.run()
  jNeuroML >>  (INFO) NRN Error  >>>   File "/tmp/tmpfxjbyyg4/fixtures/tmpddygkrlp_netpyne.py", line 128, in run
  jNeuroML >>  (INFO) NRN Error  >>>     self.gids = sim.importNeuroML2SimulateAnalyze(self.nml2_file_name,self.simConfig)
  jNeuroML >>  (INFO) NRN Error  >>>   File "/home/jonrkarr/.local/lib/python3.9/site-packages/netpyne/sim/wrappers.py", line 558, in importNeuroML2SimulateAnalyze
  jNeuroML >>  (INFO) NRN Error  >>>     return sim.importNeuroML2(fileName, simConfig, simulate=True, analyze=True)
  jNeuroML >>  (INFO) NRN Error  >>>   File "/home/jonrkarr/.local/lib/python3.9/site-packages/netpyne/conversion/neuromlFormat.py", line 1616, in importNeuroML2
  jNeuroML >>  (INFO) NRN Error  >>>     stims = sim.net.addStims()                    # add external stimulation to cells (IClamps etc)
  jNeuroML >>  (INFO) NRN Error  >>>   File "/home/jonrkarr/.local/lib/python3.9/site-packages/netpyne/network/stim.py", line 116, in addStims
  jNeuroML >>  (INFO) NRN Error  >>>     postCell.addStim(params)  # call cell method to add connection
  jNeuroML >>  (INFO) NRN Error  >>>   File "/home/jonrkarr/.local/lib/python3.9/site-packages/netpyne/cell/compartCell.py", line 1104, in addStim
  jNeuroML >>  (INFO) NRN Error  >>>     setattr(stim, stimParamName, stimParamValue)
```

**Comment by pgleeson** [comment]
PR above merged.
