### ISSUE TITLE
Python3.9: PlotSpikes.py: dictionary changed size during iteration

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#68]
Getting this when running the PlotSpikes script:

```
$ python3 ~/Documents/02_Code/00_mine/2020-OSB/NeuroML2/pyNeuroML/pyneuroml/plot/PlotSpikes.py example-izhikevich2007cell-sim.spikes.dat 
Traceback (most recent call last):
  File "/home/asinha/Documents/02_Code/00_mine/2020-OSB/NeuroML2/pyNeuroML/pyneuroml/plot/PlotSpikes.py", line 363, in <module>
    main()
  File "/home/asinha/Documents/02_Code/00_mine/2020-OSB/NeuroML2/pyNeuroML/pyneuroml/plot/PlotSpikes.py", line 112, in main
    run(a=args)
  File "/home/asinha/Documents/02_Code/00_mine/2020-OSB/NeuroML2/pyNeuroML/pyneuroml/plot/PlotSpikes.py", line 176, in run
    a = build_namespace(a, **kwargs)
  File "/home/asinha/Documents/02_Code/00_mine/2020-OSB/NeuroML2/pyNeuroML/pyneuroml/plot/PlotSpikes.py", line 48, in build_namespace
    for key, value in a.__dict__.items():
RuntimeError: dictionary changed size during iteration
```

Python3.9 here:

```
$ python3 --version
Python 3.9.1
```

Will open a PR to fix now. Just have to iterate differently, or create a new dict.

**Comment by sanjayankur31** [comment]
Note: it worked in py2, but not in py3 now:

https://stackoverflow.com/questions/11941817/how-to-avoid-runtimeerror-dictionary-changed-size-during-iteration-error
