### ISSUE TITLE
XML READ error, when running LEMS file with Neuron 

### ISSUE THREAD

**Issue by MRIO** [NeuroML/pyNeuroML#71]
Cells validate neatly and the LEMS file seems sane (e.g., LEMS_Vm_Test.xml) byt when i try

`results_dict = pynml.run_lems_with_jneuroml_neuron( rel_filename, verbose=False, nogui=True, load_saved_data=True, exec_in_dir=out_dir,         max_memory='400M')
`
I get this wacky error:

pyNeuroML >>>  jNeuroML >>  (ERROR) Can't extract content from ﻿<?xml version="1.0"

The rest of the log goes below.

```
Validating nml_C11A.net.nml against /opt/conda/lib/python3.7/site-packages/neuroml/nml/NeuroML_v2.1.xsd
It's valid!
0
pop/0/C11A/0/v
310
pop/0/C11A/310/v
pyNeuroML >>> Written LEMS Simulation Vm_Test to file: LEMS_Vm_Test.xml
/home/jovyan/work/IO-temperature-dependence
LEMS_Vm_Test.xml
pyNeuroML >>> *** Problem running command: 
pyNeuroML >>>        Command 'java -Xmx400M  -Djava.awt.headless=true -jar  "/opt/conda/lib/python3.7/site-packages/pyneuroml/lib/jNeuroML-0.10.0-jar-with-dependencies.jar"  "LEMS_Vm_Test.xml"  -neuron -run -compile -nogui' returned non-zero exit status 1.
pyNeuroML >>>  jNeuroML >>   jNeuroML v0.10.0
pyNeuroML >>>  jNeuroML >>  (INFO) Reading from: /home/jovyan/work/IO-temperature-dependence/LEMS_Vm_Test.xml
pyNeuroML >>>  jNeuroML >>  (ERROR) Can't extract content from ﻿<?xml version="1.0"
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.lemsml.jlems.core.logging.E.multiError(E.java:251)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.lemsml.jlems.core.logging.E.error(E.java:217)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.lemsml.jlems.core.sim.AbstractInclusionReader.trimOuterElement(AbstractInclusionReader.java:113)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.lemsml.jlems.core.sim.AbstractInclusionReader.getIncludeContent(AbstractInclusionReader.java:43)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.neuroml.export.utils.NeuroMLInclusionReader.insertIncludes(NeuroMLInclusionReader.java:93)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.lemsml.jlems.core.sim.AbstractInclusionReader.getIncludeContent(AbstractInclusionReader.java:42)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.neuroml.export.utils.NeuroMLInclusionReader.insertIncludes(NeuroMLInclusionReader.java:93)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.lemsml.jlems.core.sim.AbstractInclusionReader.getIncludeContent(AbstractInclusionReader.java:42)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.neuroml.export.utils.NeuroMLInclusionReader.insertIncludes(NeuroMLInclusionReader.java:93)
pyNeuroML >>>  jNeuroML >>  (LOG)   at org.lemsml.jlems.core.sim.AbstractInclusionReader.getIncludeContent(AbstractInclusionReader.java:42)
pyNeuroML >>>  jNeuroML >>  org.lemsml.jlems.core.sim.ContentError: No such type ExpTime, 227 existing types: 
```

**Comment by MRIO** [comment]
The LEMS file doesn't even have the offending <?xml version="1.0" tag

**Comment by pgleeson** [comment]
Think it doesn't matter about the ?xml tag... It's probably more to do with the line: 

      ContentError: No such type ExpTime

Where is the code that's throwing the error?

**Comment by MRIO** [comment]
Oh, indeed! Path problems in the generation of the LEMS file. I seem to often run into those, because i want to be able to point to different directories to execute.

As i know read in the file below, I save the LEMS file at the root, but the mechanisms are inside NMLfiles/Cells  —

From: LEMS_Vm_Test.xml

```

<Lems>
    
    <!-- 

        This LEMS file has been automatically generated using PyNeuroML v0.5.3 (libNeuroML v0.2.51)

     -->
    
    <!-- Specify which component to run -->
    <Target component="Vm_Test"/>

    <!-- Include core NeuroML2 ComponentType definitions -->
    <Include file="Cells.xml"/>
    <Include file="Networks.xml"/>
    <Include file="Simulation.xml"/>
    
    <Include file="NMLfiles/Cells/nml_C51A.net.nml"/>
    <Include file="C51A_scaled_exp_resample_5.cell.nml"/>
    <Include file="na_s.channel.nml"/>
    <Include file="ExpTime.nml”/>
…
```



Now i run into another issue (probably incompetence, but bear with me). I seem not to be able to point to the correct dir in which to execute. I have a type error when i try to pass a string to exec_in_dir. What i am doing wrong here?

exec_dir = "/home/jovyan/work/IO-temperature-dependence/NLMfiles/Cells”

> type(exec_dir)
> str

```
#Run LEMS file with Neuron
results_dict = pynml.run_lems_with_jneuroml_neuron(
    rel_filename, verbose=False, nogui=True, load_saved_data=True,  exec_in_dir=exec_dir,
    max_memory='400M’)
```

> TypeError: can only concatenate str (not "list") to str

**Comment by MRIO** [comment]
So, i'm trying to point to the 

FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/IO-temperature-dependence/NLMfiles/Cells/LEMS_Vm_Test.xml': '/home/jovyan/work/IO-temperature-dependence/NLMfiles/Cells/LEMS_Vm_Test.xml'

**Comment by MRIO** [comment]
> Think it doesn't matter about the ?xml tag... It's probably more to do with the line:
> 
> ```
>   ContentError: No such type ExpTime
> ```
> 
> Where is the code that's throwing the error?

https://github.com/MRIO/IO-temperature-dependence

InvestigateCellBehaviour.ipynb

**Comment by pgleeson** [comment]
@MRIO Is this working now? The simplest way to test this is to just generate the lems file and to test, run it from command line in the folder you generated it with jnml or pynml. Then if it's all good try the scripting option for running. 

It may be possible with current options to generate the lems in folder A, include files in folder B, run it from folder C and save results to folder D, but likely something will go wrong along the way, so best to keep the file structure simple (certainly you can have cells & channels, etc. in subfolders), but generate the LEMS file in the folder you plan to run it.
